"""TRex STL profile for manifests generated by trex_adapter.py.

Example:
  sudo ./t-rex-64 -f trex_gtpu_profile.py -m 1 \
    -t manifest=/tmp/trex-sessions.json,traffic_direction=uplink,src_mac=...,dst_mac=...
"""
import argparse
import json


def gtp_header(teid, inner_length):
    if not 0 <= int(teid) <= 0xffffffff:
        raise ValueError('TEID must be a 32-bit unsigned integer')
    if not 0 <= inner_length <= 0xffff:
        raise ValueError('inner packet is too large for GTP-U')
    return b'\x30\xff' + inner_length.to_bytes(2, 'big') + int(teid).to_bytes(4, 'big')


class EnbGtpuProfile:
    def get_streams(self, tunables, **kwargs):
        from trex_stl_lib.api import (
            Ether, IP, UDP, Raw, STLStream, STLPktBuilder, STLTXCont)

        parser = argparse.ArgumentParser(description='eNB GTP-U bearer profile')
        parser.add_argument('--manifest', required=True)
        parser.add_argument(
            '--traffic-direction', '--traffic_direction',
            choices=('uplink', 'downlink'), default='uplink')
        parser.add_argument('--src-mac', '--src_mac', required=True)
        parser.add_argument('--dst-mac', '--dst_mac', required=True)
        parser.add_argument('--server-ip', '--server_ip', default='198.18.0.1')
        args = parser.parse_args(tunables)
        with open(args.manifest, encoding='utf-8') as source:
            manifest = json.load(source)
        traffic = manifest['traffic']
        payload_size = int(traffic['inner_payload_size'])
        if payload_size < 28:
            raise ValueError('inner_payload_size must be at least 28 bytes')
        pps_key = f'{args.traffic_direction}_pps_per_bearer'
        streams = []
        for session in manifest['sessions']:
            if args.traffic_direction == 'uplink':
                outer_src, outer_dst = session['enb_gtpu_ip'], session['upf_ip']
                inner_src, inner_dst = session['ue_ip'], args.server_ip
                teid = session['uplink_teid']
            else:
                inner_src, inner_dst = args.server_ip, session['ue_ip']
            padding = b'\x00' * (payload_size - 28)
            inner_packet = (IP(src=inner_src, dst=inner_dst) /
                            UDP(sport=1024, dport=9000) / Raw(padding))
            if args.traffic_direction == 'uplink':
                inner = bytes(inner_packet)
                packet = (Ether(src=args.src_mac, dst=args.dst_mac) /
                          IP(src=outer_src, dst=outer_dst) /
                          UDP(sport=2152, dport=2152) /
                          Raw(gtp_header(teid, len(inner)) + inner))
            else:
                # N6 input: the UPF under test must perform downlink GTP-U encapsulation.
                packet = Ether(src=args.src_mac, dst=args.dst_mac) / inner_packet
            streams.append(STLStream(
                packet=STLPktBuilder(pkt=packet),
                mode=STLTXCont(pps=float(traffic[pps_key]))))
        return streams


def register():
    return EnbGtpuProfile()
